language: node_js
node_js:
  - "6"
  - "8"
  - "10"
branches:
  only:
    - gh-pages # needs to be explicitely included
    - /.*/
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  name: Robot Fairhurst
  keep-history: true
  on:
    # Only deploy from gh-pages branch itself
    branch: gh-pages
    # Don't deploy if the last commit is by Travis itself
    condition:  $(git log --format="%cn" -n 1) != "Robot Fairhurst (from Travis CI)"
